/* Generated by tooling/abi from the declarative ABI catalog. Do not edit. */
#ifndef NERI_ABI_CATALOG_H
#define NERI_ABI_CATALOG_H

#include <stdint.h>
#include <string.h>

#define NERI_RUNTIME_ABI_MAJOR UINT16_C(1)
#define NERI_RUNTIME_ABI_MINOR UINT16_C(25)

enum neri_ir_effect_v1 {
  NERI_IR_EFFECT_READ_V1 = UINT32_C(1),
  NERI_IR_EFFECT_WRITE_V1 = UINT32_C(2),
  NERI_IR_EFFECT_MAY_PANIC_V1 = UINT32_C(4),
  NERI_IR_EFFECT_MANAGED_ALLOCATE_V1 = UINT32_C(8),
  NERI_IR_EFFECT_NATIVE_ALLOCATE_V1 = UINT32_C(16),
  NERI_IR_EFFECT_SAFEPOINT_V1 = UINT32_C(32),
  NERI_IR_EFFECT_UNSAFE_V1 = UINT32_C(64),
  NERI_IR_EFFECT_NO_RETURN_V1 = UINT32_C(128)
};

#define NERI_RT_FEATURE_PRECISE_GC UINT64_C(1)
#define NERI_RT_FEATURE_NONMOVING_GC (UINT64_C(1) << 1)
#define NERI_RT_FEATURE_SCOPED_BORROWS (UINT64_C(1) << 2)
#define NERI_RT_FEATURE_NATIVE_MEMORY (UINT64_C(1) << 3)
#define NERI_RT_FEATURE_ROOT_FRAMES (UINT64_C(1) << 4)
#define NERI_RT_FEATURE_SOURCE_LOCATIONS (UINT64_C(1) << 5)
#define NERI_RT_FEATURE_NATIVE_STRINGS (UINT64_C(1) << 6)
#define NERI_RT_FEATURE_CONSOLE_IO (UINT64_C(1) << 7)
#define NERI_RT_FEATURE_INLINE_AGGREGATES (UINT64_C(1) << 8)
#define NERI_RT_FEATURE_EXTENDED_SCALARS (UINT64_C(1) << 9)
#define NERI_RT_FEATURE_MULTIPLE_MUTATORS (UINT64_C(1) << 10)
#define NERI_RT_FEATURE_BOOTSTRAP_HOST (UINT64_C(1) << 11)
#define NERI_RT_FEATURE_SOCKETS (UINT64_C(1) << 12)
#define NERI_RT_FEATURE_INTERACTIVE_IO (UINT64_C(1) << 13)
#define NERI_RT_FEATURE_SCOPED_TASKS (UINT64_C(1) << 14)
#define NERI_RT_FEATURE_FILES (UINT64_C(1) << 15)
#define NERI_RT_FEATURE_INTERRUPTS (UINT64_C(1) << 16)
#define NERI_RT_FEATURE_WALL_CLOCK (UINT64_C(1) << 17)
#define NERI_RT_FEATURE_CRYPTO (UINT64_C(1) << 18)
#define NERI_RT_FEATURE_ROOTED_FILES (UINT64_C(1) << 19)
#define NERI_RT_FEATURE_PROCESS (UINT64_C(1) << 20)
#define NERI_RT_FEATURE_DIRECTORY (UINT64_C(1) << 21)
#define NERI_RT_FEATURE_SOCKET_CLOSE_RESULT (UINT64_C(1) << 22)
#define NERI_RT_FEATURE_SESSION_MODULES (UINT64_C(1) << 23)
#define NERI_RT_FEATURE_DRAIN (UINT64_C(1) << 24)
#define NERI_RT_FEATURE_OPTIONAL_CONSOLE_READ (UINT64_C(1) << 25)
#define NERI_RT_FEATURE_PROCESS_IO (UINT64_C(1) << 26)
#define NERI_RT_FEATURE_FILESYSTEM_MUTATION (UINT64_C(1) << 27)
#define NERI_RT_FEATURE_SOCKET_ENDPOINTS (UINT64_C(1) << 28)
#define NERI_RT_ADVERTISED_FEATURES UINT64_C(536869631)

static inline uint16_t neri_abi_symbol_minimum_minor(const char *link_name) {
  uint16_t result = UINT16_C(0);
  if (link_name == NULL) return result;
  if (strncmp(link_name, "neri_rt_v1_file_", sizeof("neri_rt_v1_file_") - 1U) == 0 && result < UINT16_C(11)) result = UINT16_C(11);
  if (strcmp(link_name, "neri_rt_v1_file_wait_readable") == 0 && result < UINT16_C(25)) result = UINT16_C(25);
  if (strncmp(link_name, "neri_rt_v1_interrupt_", sizeof("neri_rt_v1_interrupt_") - 1U) == 0 && result < UINT16_C(12)) result = UINT16_C(12);
  if (strncmp(link_name, "neri_rt_v1_clock_wall_", sizeof("neri_rt_v1_clock_wall_") - 1U) == 0 && result < UINT16_C(13)) result = UINT16_C(13);
  if (strncmp(link_name, "neri_rt_v1_crypto_", sizeof("neri_rt_v1_crypto_") - 1U) == 0 && result < UINT16_C(14)) result = UINT16_C(14);
  if (strncmp(link_name, "neri_rt_v1_file_root_", sizeof("neri_rt_v1_file_root_") - 1U) == 0 && result < UINT16_C(15)) result = UINT16_C(15);
  if (strncmp(link_name, "neri_rt_v1_process_", sizeof("neri_rt_v1_process_") - 1U) == 0 && result < UINT16_C(16)) result = UINT16_C(16);
  if (strcmp(link_name, "neri_rt_v1_process_spawn_input") == 0 && result < UINT16_C(22)) result = UINT16_C(22);
  if (strcmp(link_name, "neri_rt_v1_process_interrupt") == 0 && result < UINT16_C(22)) result = UINT16_C(22);
  if (strncmp(link_name, "neri_rt_v1_file_mutation_", sizeof("neri_rt_v1_file_mutation_") - 1U) == 0 && result < UINT16_C(22)) result = UINT16_C(22);
  if (strcmp(link_name, "neri_rt_v1_net_connect_timeout") == 0 && result < UINT16_C(22)) result = UINT16_C(22);
  if (strcmp(link_name, "neri_rt_v1_net_local_port") == 0 && result < UINT16_C(22)) result = UINT16_C(22);
  if (strncmp(link_name, "neri_rt_v1_file_directory_", sizeof("neri_rt_v1_file_directory_") - 1U) == 0 && result < UINT16_C(17)) result = UINT16_C(17);
  if (strcmp(link_name, "neri_rt_v1_net_close_result") == 0 && result < UINT16_C(18)) result = UINT16_C(18);
  if (strncmp(link_name, "neri_rt_v1_drain_", sizeof("neri_rt_v1_drain_") - 1U) == 0 && result < UINT16_C(20)) result = UINT16_C(20);
  if (strncmp(link_name, "neri_rt_v1_session_", sizeof("neri_rt_v1_session_") - 1U) == 0 && result < UINT16_C(19)) result = UINT16_C(19);
  if (strcmp(link_name, "neri_rt_v1_stdin_read_line_optional") == 0 && result < UINT16_C(21)) result = UINT16_C(21);
  if (strcmp(link_name, "neri_rt_v1_host_canonical_path") == 0 && result < UINT16_C(23)) result = UINT16_C(23);
  if (strncmp(link_name, "neri_rt_v1_terminal_", sizeof("neri_rt_v1_terminal_") - 1U) == 0 && result < UINT16_C(8)) result = UINT16_C(8);
  if (strncmp(link_name, "neri_rt_v1_clock_", sizeof("neri_rt_v1_clock_") - 1U) == 0 && result < UINT16_C(8)) result = UINT16_C(8);
  if (strncmp(link_name, "neri_rt_v1_net_", sizeof("neri_rt_v1_net_") - 1U) == 0 && result < UINT16_C(7)) result = UINT16_C(7);
  return result;
}

static inline uint64_t neri_abi_symbol_features(const char *link_name) {
  uint64_t result = UINT64_C(0);
  if (link_name == NULL) return result;
  if (strncmp(link_name, "neri_rt_v1_file_", sizeof("neri_rt_v1_file_") - 1U) == 0) result |= NERI_RT_FEATURE_FILES;
  if (strncmp(link_name, "neri_rt_v1_interrupt_", sizeof("neri_rt_v1_interrupt_") - 1U) == 0) result |= NERI_RT_FEATURE_INTERRUPTS;
  if (strncmp(link_name, "neri_rt_v1_clock_wall_", sizeof("neri_rt_v1_clock_wall_") - 1U) == 0) result |= NERI_RT_FEATURE_WALL_CLOCK;
  if (strncmp(link_name, "neri_rt_v1_crypto_", sizeof("neri_rt_v1_crypto_") - 1U) == 0) result |= NERI_RT_FEATURE_CRYPTO;
  if (strncmp(link_name, "neri_rt_v1_file_root_", sizeof("neri_rt_v1_file_root_") - 1U) == 0) result |= NERI_RT_FEATURE_ROOTED_FILES;
  if (strncmp(link_name, "neri_rt_v1_process_", sizeof("neri_rt_v1_process_") - 1U) == 0) result |= NERI_RT_FEATURE_PROCESS;
  if (strcmp(link_name, "neri_rt_v1_process_spawn_input") == 0) result |= NERI_RT_FEATURE_PROCESS_IO;
  if (strcmp(link_name, "neri_rt_v1_process_interrupt") == 0) result |= NERI_RT_FEATURE_PROCESS_IO;
  if (strncmp(link_name, "neri_rt_v1_file_mutation_", sizeof("neri_rt_v1_file_mutation_") - 1U) == 0) result |= NERI_RT_FEATURE_FILESYSTEM_MUTATION;
  if (strcmp(link_name, "neri_rt_v1_net_connect_timeout") == 0) result |= NERI_RT_FEATURE_SOCKET_ENDPOINTS;
  if (strcmp(link_name, "neri_rt_v1_net_local_port") == 0) result |= NERI_RT_FEATURE_SOCKET_ENDPOINTS;
  if (strncmp(link_name, "neri_rt_v1_file_directory_", sizeof("neri_rt_v1_file_directory_") - 1U) == 0) result |= NERI_RT_FEATURE_DIRECTORY;
  if (strcmp(link_name, "neri_rt_v1_net_close_result") == 0) result |= NERI_RT_FEATURE_SOCKET_CLOSE_RESULT;
  if (strncmp(link_name, "neri_rt_v1_drain_", sizeof("neri_rt_v1_drain_") - 1U) == 0) result |= NERI_RT_FEATURE_DRAIN;
  if (strncmp(link_name, "neri_rt_v1_session_", sizeof("neri_rt_v1_session_") - 1U) == 0) result |= NERI_RT_FEATURE_SESSION_MODULES;
  if (strcmp(link_name, "neri_rt_v1_stdin_read_line_optional") == 0) result |= NERI_RT_FEATURE_OPTIONAL_CONSOLE_READ;
  if (strcmp(link_name, "neri_rt_v1_host_canonical_path") == 0) result |= NERI_RT_FEATURE_BOOTSTRAP_HOST;
  if (strncmp(link_name, "neri_rt_v1_terminal_", sizeof("neri_rt_v1_terminal_") - 1U) == 0) result |= NERI_RT_FEATURE_INTERACTIVE_IO;
  if (strncmp(link_name, "neri_rt_v1_clock_", sizeof("neri_rt_v1_clock_") - 1U) == 0) result |= NERI_RT_FEATURE_INTERACTIVE_IO;
  if (strncmp(link_name, "neri_rt_v1_net_", sizeof("neri_rt_v1_net_") - 1U) == 0) result |= NERI_RT_FEATURE_SOCKETS;
  return result;
}

#endif
