/* Generated by tooling/abi from the declarative ABI catalog. Do not edit. */
#ifndef NERI_ABI_RUNTIME_IMPORTS_H
#define NERI_ABI_RUNTIME_IMPORTS_H

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "neri/abi_catalog.h"
#include "neri/ir_transport.h"

struct neri_abi_type_v1 {
  uint8_t tag;
  const struct neri_abi_type_v1 *argument;
};

struct neri_abi_runtime_import_v1 {
  const char *link_name;
  const struct neri_abi_type_v1 *parameter_types;
  uint32_t parameter_count;
  struct neri_abi_type_v1 result_type;
  uint32_t effects;
  uint16_t minimum_minor;
  uint64_t feature_bits;
};

static const struct neri_abi_type_v1 neri_abi_type_bool_v1 = { NERI_IR_TYPE_BOOL_V1, NULL };
static const struct neri_abi_type_v1 neri_abi_type_byte_v1 = { NERI_IR_TYPE_BYTE_V1, NULL };
static const struct neri_abi_type_v1 neri_abi_type_int_v1 = { NERI_IR_TYPE_INT_V1, NULL };
static const struct neri_abi_type_v1 neri_abi_type_float_v1 = { NERI_IR_TYPE_FLOAT_V1, NULL };
static const struct neri_abi_type_v1 neri_abi_type_string_v1 = { NERI_IR_TYPE_STRING_V1, NULL };

static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_string_concat[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_string_equal[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_string_byte_length[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_string_byte_at[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_string_slice[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
  { NERI_IR_TYPE_INT_V1, NULL },
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_string_from_bytes[] = {
  { NERI_IR_TYPE_ARRAY_V1, &neri_abi_type_byte_v1 },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_stdout_write[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_stdout_write_line[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_math_abs[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_math_max[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_math_min[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_math_pow[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_test_assert[] = {
  { NERI_IR_TYPE_BOOL_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_test_assert_true[] = {
  { NERI_IR_TYPE_BOOL_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_test_assert_false[] = {
  { NERI_IR_TYPE_BOOL_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_exit[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_read_text[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_path_join[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_path_absolute[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_path_file_name[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_argument_at[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_environment[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_parse_int[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_parse_float[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_run[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
  { NERI_IR_TYPE_ARRAY_V1, &neri_abi_type_string_v1 },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_append_byte[] = {
  { NERI_IR_TYPE_ARRAY_V1, &neri_abi_type_byte_v1 },
  { NERI_IR_TYPE_BYTE_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_append_int[] = {
  { NERI_IR_TYPE_ARRAY_V1, &neri_abi_type_int_v1 },
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_append_string[] = {
  { NERI_IR_TYPE_ARRAY_V1, &neri_abi_type_string_v1 },
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_write_text[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_write_bytes[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
  { NERI_IR_TYPE_ARRAY_V1, &neri_abi_type_byte_v1 },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_host_remove_file[] = {
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_session_owner[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_session_load_execute[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_session_load_execute_retained[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
  { NERI_IR_TYPE_STRING_V1, NULL },
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_session_load_execute_object[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
  { NERI_IR_TYPE_STRING_V1, NULL },
  { NERI_IR_TYPE_STRING_V1, NULL },
  { NERI_IR_TYPE_STRING_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_session_reset[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_session_destroy[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_session_error[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
};
static const struct neri_abi_type_v1 neri_abi_parameters_neri_rt_v1_session_result[] = {
  { NERI_IR_TYPE_INT_V1, NULL },
};

static const struct neri_abi_runtime_import_v1 neri_abi_runtime_imports_v1[] = {
  { "neri_rt_v1_string_concat", neri_abi_parameters_neri_rt_v1_string_concat, UINT32_C(2), { NERI_IR_TYPE_STRING_V1, NULL }, UINT32_C(44), UINT16_C(2), UINT64_C(0) },
  { "neri_rt_v1_string_equal", neri_abi_parameters_neri_rt_v1_string_equal, UINT32_C(2), { NERI_IR_TYPE_BOOL_V1, NULL }, UINT32_C(1), UINT16_C(2), UINT64_C(0) },
  { "neri_rt_v1_host_string_byte_length", neri_abi_parameters_neri_rt_v1_host_string_byte_length, UINT32_C(1), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(4), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_string_byte_at", neri_abi_parameters_neri_rt_v1_host_string_byte_at, UINT32_C(2), { NERI_IR_TYPE_BYTE_V1, NULL }, UINT32_C(4), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_string_slice", neri_abi_parameters_neri_rt_v1_host_string_slice, UINT32_C(3), { NERI_IR_TYPE_STRING_V1, NULL }, UINT32_C(44), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_string_from_bytes", neri_abi_parameters_neri_rt_v1_host_string_from_bytes, UINT32_C(1), { NERI_IR_TYPE_OPTIONAL_V1, &neri_abi_type_string_v1 }, UINT32_C(44), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_stdout_write", neri_abi_parameters_neri_rt_v1_stdout_write, UINT32_C(1), { NERI_IR_TYPE_VOID_V1, NULL }, UINT32_C(6), UINT16_C(3), UINT64_C(128) },
  { "neri_rt_v1_stdout_write_line", neri_abi_parameters_neri_rt_v1_stdout_write_line, UINT32_C(1), { NERI_IR_TYPE_VOID_V1, NULL }, UINT32_C(6), UINT16_C(3), UINT64_C(128) },
  { "neri_rt_v1_stdin_read_line", NULL, UINT32_C(0), { NERI_IR_TYPE_STRING_V1, NULL }, UINT32_C(45), UINT16_C(4), UINT64_C(192) },
  { "neri_rt_v1_stdin_read_line_optional", NULL, UINT32_C(0), { NERI_IR_TYPE_OPTIONAL_V1, &neri_abi_type_string_v1 }, UINT32_C(45), UINT16_C(21), UINT64_C(33554432) },
  { "neri_rt_v1_math_abs", neri_abi_parameters_neri_rt_v1_math_abs, UINT32_C(1), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(4), UINT16_C(4), UINT64_C(0) },
  { "neri_rt_v1_math_max", neri_abi_parameters_neri_rt_v1_math_max, UINT32_C(2), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(0), UINT16_C(4), UINT64_C(0) },
  { "neri_rt_v1_math_min", neri_abi_parameters_neri_rt_v1_math_min, UINT32_C(2), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(0), UINT16_C(4), UINT64_C(0) },
  { "neri_rt_v1_math_pow", neri_abi_parameters_neri_rt_v1_math_pow, UINT32_C(2), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(4), UINT16_C(4), UINT64_C(0) },
  { "neri_rt_v1_test_assert", neri_abi_parameters_neri_rt_v1_test_assert, UINT32_C(1), { NERI_IR_TYPE_VOID_V1, NULL }, UINT32_C(4), UINT16_C(4), UINT64_C(0) },
  { "neri_rt_v1_test_assert_true", neri_abi_parameters_neri_rt_v1_test_assert_true, UINT32_C(1), { NERI_IR_TYPE_VOID_V1, NULL }, UINT32_C(4), UINT16_C(4), UINT64_C(0) },
  { "neri_rt_v1_test_assert_false", neri_abi_parameters_neri_rt_v1_test_assert_false, UINT32_C(1), { NERI_IR_TYPE_VOID_V1, NULL }, UINT32_C(4), UINT16_C(4), UINT64_C(0) },
  { "neri_rt_v1_host_exit", neri_abi_parameters_neri_rt_v1_host_exit, UINT32_C(1), { NERI_IR_TYPE_VOID_V1, NULL }, UINT32_C(134), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_argument_count", NULL, UINT32_C(0), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(1), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_error_message", NULL, UINT32_C(0), { NERI_IR_TYPE_STRING_V1, NULL }, UINT32_C(45), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_read_text", neri_abi_parameters_neri_rt_v1_host_read_text, UINT32_C(1), { NERI_IR_TYPE_OPTIONAL_V1, &neri_abi_type_string_v1 }, UINT32_C(45), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_path_join", neri_abi_parameters_neri_rt_v1_host_path_join, UINT32_C(2), { NERI_IR_TYPE_OPTIONAL_V1, &neri_abi_type_string_v1 }, UINT32_C(44), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_path_absolute", neri_abi_parameters_neri_rt_v1_host_path_absolute, UINT32_C(1), { NERI_IR_TYPE_OPTIONAL_V1, &neri_abi_type_string_v1 }, UINT32_C(45), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_path_file_name", neri_abi_parameters_neri_rt_v1_host_path_file_name, UINT32_C(1), { NERI_IR_TYPE_OPTIONAL_V1, &neri_abi_type_string_v1 }, UINT32_C(44), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_argument_at", neri_abi_parameters_neri_rt_v1_host_argument_at, UINT32_C(1), { NERI_IR_TYPE_OPTIONAL_V1, &neri_abi_type_string_v1 }, UINT32_C(45), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_environment", neri_abi_parameters_neri_rt_v1_host_environment, UINT32_C(1), { NERI_IR_TYPE_OPTIONAL_V1, &neri_abi_type_string_v1 }, UINT32_C(45), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_parse_int", neri_abi_parameters_neri_rt_v1_host_parse_int, UINT32_C(1), { NERI_IR_TYPE_OPTIONAL_V1, &neri_abi_type_int_v1 }, UINT32_C(4), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_parse_float", neri_abi_parameters_neri_rt_v1_host_parse_float, UINT32_C(1), { NERI_IR_TYPE_OPTIONAL_V1, &neri_abi_type_float_v1 }, UINT32_C(4), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_run", neri_abi_parameters_neri_rt_v1_host_run, UINT32_C(2), { NERI_IR_TYPE_OPTIONAL_V1, &neri_abi_type_int_v1 }, UINT32_C(7), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_append_byte", neri_abi_parameters_neri_rt_v1_host_append_byte, UINT32_C(2), { NERI_IR_TYPE_ARRAY_V1, &neri_abi_type_byte_v1 }, UINT32_C(44), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_append_int", neri_abi_parameters_neri_rt_v1_host_append_int, UINT32_C(2), { NERI_IR_TYPE_ARRAY_V1, &neri_abi_type_int_v1 }, UINT32_C(44), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_append_string", neri_abi_parameters_neri_rt_v1_host_append_string, UINT32_C(2), { NERI_IR_TYPE_ARRAY_V1, &neri_abi_type_string_v1 }, UINT32_C(44), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_write_text", neri_abi_parameters_neri_rt_v1_host_write_text, UINT32_C(2), { NERI_IR_TYPE_BOOL_V1, NULL }, UINT32_C(6), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_write_bytes", neri_abi_parameters_neri_rt_v1_host_write_bytes, UINT32_C(2), { NERI_IR_TYPE_BOOL_V1, NULL }, UINT32_C(6), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_host_remove_file", neri_abi_parameters_neri_rt_v1_host_remove_file, UINT32_C(1), { NERI_IR_TYPE_BOOL_V1, NULL }, UINT32_C(6), UINT16_C(6), UINT64_C(2048) },
  { "neri_rt_v1_session_identity", NULL, UINT32_C(0), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(84), UINT16_C(19), UINT64_C(8388608) },
  { "neri_rt_v1_session_create", NULL, UINT32_C(0), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(84), UINT16_C(19), UINT64_C(8388608) },
  { "neri_rt_v1_session_owner", neri_abi_parameters_neri_rt_v1_session_owner, UINT32_C(1), { NERI_IR_TYPE_STRING_V1, NULL }, UINT32_C(93), UINT16_C(19), UINT64_C(8388608) },
  { "neri_rt_v1_session_load_execute", neri_abi_parameters_neri_rt_v1_session_load_execute, UINT32_C(2), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(125), UINT16_C(19), UINT64_C(8388608) },
  { "neri_rt_v1_session_load_execute_retained", neri_abi_parameters_neri_rt_v1_session_load_execute_retained, UINT32_C(3), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(125), UINT16_C(23), UINT64_C(8388608) },
  { "neri_rt_v1_session_load_execute_object", neri_abi_parameters_neri_rt_v1_session_load_execute_object, UINT32_C(4), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(125), UINT16_C(24), UINT64_C(8388608) },
  { "neri_rt_v1_session_reset", neri_abi_parameters_neri_rt_v1_session_reset, UINT32_C(1), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(125), UINT16_C(19), UINT64_C(8388608) },
  { "neri_rt_v1_session_destroy", neri_abi_parameters_neri_rt_v1_session_destroy, UINT32_C(1), { NERI_IR_TYPE_INT_V1, NULL }, UINT32_C(125), UINT16_C(19), UINT64_C(8388608) },
  { "neri_rt_v1_session_error", neri_abi_parameters_neri_rt_v1_session_error, UINT32_C(1), { NERI_IR_TYPE_STRING_V1, NULL }, UINT32_C(93), UINT16_C(19), UINT64_C(8388608) },
  { "neri_rt_v1_session_result", neri_abi_parameters_neri_rt_v1_session_result, UINT32_C(1), { NERI_IR_TYPE_STRING_V1, NULL }, UINT32_C(93), UINT16_C(23), UINT64_C(8388608) },
};

static inline const struct neri_abi_runtime_import_v1 *neri_abi_runtime_import(const char *link_name) {
  if (link_name == NULL) return NULL;
  for (size_t index = 0; index < sizeof(neri_abi_runtime_imports_v1) / sizeof(neri_abi_runtime_imports_v1[0]); ++index) {
    if (strcmp(link_name, neri_abi_runtime_imports_v1[index].link_name) == 0) return &neri_abi_runtime_imports_v1[index];
  }
  return NULL;
}

#endif
