/* Generated by tooling/abi. Do not edit. */
#ifndef NERI_IR_PROTOCOL_H
#define NERI_IR_PROTOCOL_H

#include <stdint.h>

#define NERI_IR_SEMANTIC_MAJOR_V1 UINT16_C(1)
#define NERI_IR_SEMANTIC_MINOR_V1 UINT16_C(0)
#define NERI_IR_TRANSPORT_MAJOR_V1 UINT16_C(1)
#define NERI_IR_TRANSPORT_MINOR_V1 UINT16_C(9)

#endif
