#ifndef NERI_IR_TRANSPORT_H
#define NERI_IR_TRANSPORT_H

#include <stdint.h>

/* Canonical Neri IR transport v1 constants. Never parse the header by casting a C struct. */
#define NERI_IR_TRANSPORT_MAJOR_V1 UINT16_C(1)
#define NERI_IR_TRANSPORT_MINOR_V1 UINT16_C(2)
#define NERI_IR_HEADER_SIZE_V1 UINT32_C(56)
#define NERI_IR_DIGEST_SIZE_V1 UINT32_C(32)
#define NERI_IR_VERSION_MAJOR_OFFSET_V1 UINT32_C(8)
#define NERI_IR_VERSION_MINOR_OFFSET_V1 UINT32_C(10)
#define NERI_IR_FLAGS_OFFSET_V1 UINT32_C(12)
#define NERI_IR_PAYLOAD_LENGTH_OFFSET_V1 UINT32_C(16)
#define NERI_IR_DIGEST_OFFSET_V1 UINT32_C(24)

static const uint8_t NERI_IR_MAGIC_V1[8] = {
    UINT8_C(0x4e), UINT8_C(0x45), UINT8_C(0x52), UINT8_C(0x49),
    UINT8_C(0x52), UINT8_C(0x0d), UINT8_C(0x0a), UINT8_C(0x1a),
};

enum neri_ir_symbol_kind_v1 {
    NERI_IR_SYMBOL_CLASS_V1 = 1,
    NERI_IR_SYMBOL_FIELD_V1 = 2,
    NERI_IR_SYMBOL_METHOD_V1 = 3,
    NERI_IR_SYMBOL_FUNCTION_V1 = 4,
    NERI_IR_SYMBOL_PARAMETER_V1 = 5,
    NERI_IR_SYMBOL_LOCAL_V1 = 6,
    NERI_IR_SYMBOL_LIBRARY_FUNCTION_V1 = 7,
    NERI_IR_SYMBOL_INTRINSIC_V1 = 8,
    NERI_IR_SYMBOL_GLOBAL_V1 = 9,
};

enum neri_ir_access_v1 {
    NERI_IR_ACCESS_PUBLIC_V1 = 1,
    NERI_IR_ACCESS_PRIVATE_V1 = 2,
    NERI_IR_ACCESS_PROTECTED_V1 = 3,
    NERI_IR_ACCESS_INTERNAL_V1 = 4,
};

enum neri_ir_global_linkage_v1 {
    NERI_IR_GLOBAL_INTERNAL_V1 = 1,
    NERI_IR_GLOBAL_EXPORTED_V1 = 2,
};

enum neri_ir_import_kind_v1 {
    NERI_IR_IMPORT_RUNTIME_V1 = 1,
    NERI_IR_IMPORT_C_ABI_V1 = 2,
};

enum neri_ir_function_kind_v1 {
    NERI_IR_FUNCTION_V1 = 1,
    NERI_IR_STATIC_METHOD_V1 = 2,
    NERI_IR_INSTANCE_METHOD_V1 = 3,
    NERI_IR_CONSTRUCTOR_V1 = 4,
    NERI_IR_DEFAULT_ADAPTER_V1 = 5,
};

enum neri_ir_dispatch_kind_v1 {
    NERI_IR_DISPATCH_STATIC_V1 = 1,
    NERI_IR_DISPATCH_DIRECT_V1 = 2,
    NERI_IR_DISPATCH_VIRTUAL_V1 = 3,
};

enum neri_ir_comparison_v1 {
    NERI_IR_COMPARISON_EQUAL_V1 = 1,
    NERI_IR_COMPARISON_NOT_EQUAL_V1 = 2,
    NERI_IR_COMPARISON_LESS_V1 = 3,
    NERI_IR_COMPARISON_LESS_OR_EQUAL_V1 = 4,
    NERI_IR_COMPARISON_GREATER_V1 = 5,
    NERI_IR_COMPARISON_GREATER_OR_EQUAL_V1 = 6,
};

enum neri_ir_effect_v1 {
    NERI_IR_EFFECT_READ_V1 = UINT32_C(1) << 0U,
    NERI_IR_EFFECT_WRITE_V1 = UINT32_C(1) << 1U,
    NERI_IR_EFFECT_MAY_PANIC_V1 = UINT32_C(1) << 2U,
    NERI_IR_EFFECT_MANAGED_ALLOCATE_V1 = UINT32_C(1) << 3U,
    NERI_IR_EFFECT_NATIVE_ALLOCATE_V1 = UINT32_C(1) << 4U,
    NERI_IR_EFFECT_SAFEPOINT_V1 = UINT32_C(1) << 5U,
    NERI_IR_EFFECT_UNSAFE_V1 = UINT32_C(1) << 6U,
    NERI_IR_EFFECT_NO_RETURN_V1 = UINT32_C(1) << 7U,
};

enum neri_ir_type_tag_v1 {
    NERI_IR_TYPE_VOID_V1 = 1,
    NERI_IR_TYPE_BOOL_V1 = 2,
    NERI_IR_TYPE_BYTE_V1 = 3,
    NERI_IR_TYPE_INT_V1 = 4,
    NERI_IR_TYPE_FLOAT_V1 = 5,
    NERI_IR_TYPE_STRING_V1 = 6,
    NERI_IR_TYPE_INT32_V1 = 7,
    NERI_IR_TYPE_UINT32_V1 = 8,
    NERI_IR_TYPE_UINT64_V1 = 9,
    NERI_IR_TYPE_FLOAT32_V1 = 10,
    NERI_IR_TYPE_ARRAY_V1 = 16,
    NERI_IR_TYPE_CLASS_V1 = 17,
    NERI_IR_TYPE_OPTIONAL_V1 = 18,
    NERI_IR_TYPE_POINTER_V1 = 19,
    NERI_IR_TYPE_UNSAFE_CAPABILITY_V1 = 32,
    NERI_IR_TYPE_BORROW_CAPABILITY_V1 = 33,
};

enum neri_ir_constant_tag_v1 {
    NERI_IR_CONSTANT_BOOL_V1 = 1,
    NERI_IR_CONSTANT_BYTE_V1 = 2,
    NERI_IR_CONSTANT_INT_V1 = 3,
    NERI_IR_CONSTANT_FLOAT_V1 = 4,
    NERI_IR_CONSTANT_OPTIONAL_NONE_V1 = 5,
    NERI_IR_CONSTANT_OPTIONAL_SOME_V1 = 6,
    NERI_IR_CONSTANT_STRING_GLOBAL_V1 = 7,
    NERI_IR_CONSTANT_STRING_UTF8_V1 = 8,
};

enum neri_ir_terminator_tag_v1 {
    NERI_IR_TERMINATOR_BRANCH_V1 = 1,
    NERI_IR_TERMINATOR_CONDITIONAL_BRANCH_V1 = 2,
    NERI_IR_TERMINATOR_RETURN_V1 = 3,
    NERI_IR_TERMINATOR_PANIC_V1 = 4,
};

enum neri_ir_opcode_v1 {
    NERI_IR_OPCODE_CONSTANT_V1 = 1,
    NERI_IR_OPCODE_INT_NEG_CHECKED_V1 = 2,
    NERI_IR_OPCODE_INT_ADD_CHECKED_V1 = 3,
    NERI_IR_OPCODE_INT_SUB_CHECKED_V1 = 4,
    NERI_IR_OPCODE_INT_MUL_CHECKED_V1 = 5,
    NERI_IR_OPCODE_INT_DIV_CHECKED_V1 = 6,
    NERI_IR_OPCODE_FLOAT_NEG_V1 = 7,
    NERI_IR_OPCODE_FLOAT_ADD_V1 = 8,
    NERI_IR_OPCODE_FLOAT_SUB_V1 = 9,
    NERI_IR_OPCODE_FLOAT_MUL_V1 = 10,
    NERI_IR_OPCODE_FLOAT_DIV_V1 = 11,
    NERI_IR_OPCODE_BOOL_NOT_V1 = 12,
    NERI_IR_OPCODE_BOOL_AND_V1 = 13,
    NERI_IR_OPCODE_BOOL_OR_V1 = 14,
    NERI_IR_OPCODE_COMPARE_V1 = 15,
    NERI_IR_OPCODE_CAST_INT_TO_FLOAT_V1 = 16,
    NERI_IR_OPCODE_CAST_FLOAT_TO_INT_CHECKED_V1 = 17,
    NERI_IR_OPCODE_CAST_INT_TO_BYTE_CHECKED_V1 = 18,
    NERI_IR_OPCODE_CAST_BYTE_TO_INT_V1 = 19,
    NERI_IR_OPCODE_CLASS_UPCAST_V1 = 20,
    NERI_IR_OPCODE_OPTIONAL_NONE_V1 = 21,
    NERI_IR_OPCODE_OPTIONAL_SOME_V1 = 22,
    NERI_IR_OPCODE_OPTIONAL_IS_SOME_V1 = 23,
    NERI_IR_OPCODE_OPTIONAL_GET_CHECKED_V1 = 24,
    NERI_IR_OPCODE_STRING_CONCAT_V1 = 25,
    NERI_IR_OPCODE_STRING_EQUAL_V1 = 26,
    NERI_IR_OPCODE_STRING_NOT_EQUAL_V1 = 27,
    NERI_IR_OPCODE_CALL_V1 = 28,
    NERI_IR_OPCODE_CALL_DIRECT_V1 = 29,
    NERI_IR_OPCODE_CALL_VIRTUAL_V1 = 30,
    NERI_IR_OPCODE_CALL_IMPORT_V1 = 31,
    NERI_IR_OPCODE_CALL_UNSAFE_V1 = 32,
    NERI_IR_OPCODE_CALL_C_ABI_V1 = 33,
    NERI_IR_OPCODE_ARRAY_NEW_V1 = 34,
    NERI_IR_OPCODE_ARRAY_LENGTH_V1 = 35,
    NERI_IR_OPCODE_ARRAY_LOAD_CHECKED_V1 = 36,
    NERI_IR_OPCODE_ARRAY_STORE_CHECKED_V1 = 37,
    NERI_IR_OPCODE_OBJECT_ALLOC_V1 = 38,
    NERI_IR_OPCODE_FIELD_LOAD_V1 = 39,
    NERI_IR_OPCODE_FIELD_STORE_V1 = 40,
    NERI_IR_OPCODE_UNSAFE_BEGIN_V1 = 41,
    NERI_IR_OPCODE_UNSAFE_END_V1 = 42,
    NERI_IR_OPCODE_STACK_ALLOC_V1 = 43,
    NERI_IR_OPCODE_POINTER_LOAD_V1 = 44,
    NERI_IR_OPCODE_POINTER_STORE_V1 = 45,
    NERI_IR_OPCODE_POINTER_OFFSET_V1 = 46,
    NERI_IR_OPCODE_POINTER_DIFFERENCE_V1 = 47,
    NERI_IR_OPCODE_POINTER_COMPARE_V1 = 48,
    NERI_IR_OPCODE_POINTER_CAST_V1 = 49,
    NERI_IR_OPCODE_NATIVE_ALLOC_V1 = 50,
    NERI_IR_OPCODE_NATIVE_REALLOC_V1 = 51,
    NERI_IR_OPCODE_NATIVE_FREE_V1 = 52,
    NERI_IR_OPCODE_BORROW_BEGIN_V1 = 53,
    NERI_IR_OPCODE_BORROW_END_V1 = 54,
    NERI_IR_OPCODE_STRING_FROM_INT_V1 = 55,
    NERI_IR_OPCODE_STRING_FROM_BYTE_V1 = 56,
    NERI_IR_OPCODE_STRING_FROM_FLOAT_V1 = 57,
    NERI_IR_OPCODE_NUMERIC_CAST_CHECKED_V1 = 58,
};

#endif
